export const appIconFaMap = {
  house: 'fa-house',
  key: 'fa-key',
  building: 'fa-building',
  sparkles: 'fa-wand-magic-sparkles',
  users: 'fa-users',
  leaf: 'fa-leaf',
  wifi: 'fa-wifi',
  car: 'fa-car-side',
  coffee: 'fa-mug-saucer',
  snow: 'fa-snowflake',
  flame: 'fa-fire-flame-curved',
  tv: 'fa-tv',
  kitchen: 'fa-kitchen-set',
  laptop: 'fa-laptop',
  washer: 'fa-soap',
  wind: 'fa-wind',
  breakfast: 'fa-croissant',
  moon: 'fa-moon',
  luggage: 'fa-suitcase',
  cleaning: 'fa-spray-can-sparkles',
  bus: 'fa-bus',
  plane: 'fa-plane',
  bike: 'fa-bicycle',
  parking: 'fa-square-parking',
  alert: 'fa-triangle-exclamation',
  medical: 'fa-kit-medical',
  phone: 'fa-phone',
  shield: 'fa-shield-halved',
  map: 'fa-map-location-dot',
  utensils: 'fa-utensils',
  'shopping-bag': 'fa-bag-shopping',
  camera: 'fa-camera',
  image: 'fa-image',
  info: 'fa-circle-info',
  book: 'fa-calendar-check',
  link: 'fa-bolt',
  hero: 'fa-panorama',
  text: 'fa-pen-to-square',
  spacer: 'fa-arrows-up-down',
  palette: 'fa-palette',
  globe: 'fa-globe',
  mobile: 'fa-mobile-screen-button',
  rocket: 'fa-rocket',
  lock: 'fa-shield-check',
} as const

export type AppIconName = keyof typeof appIconFaMap

export const appIconEmojiMap: Record<AppIconName, string> = {
  house: '🏠',
  key: '🗝️',
  building: '🏢',
  sparkles: '✨',
  users: '👥',
  leaf: '🍃',
  wifi: '📶',
  car: '🚗',
  coffee: '☕',
  snow: '❄️',
  flame: '🔥',
  tv: '📺',
  kitchen: '🍽️',
  laptop: '💻',
  washer: '🧼',
  wind: '💨',
  breakfast: '🥐',
  moon: '🌙',
  luggage: '🧳',
  cleaning: '🧹',
  bus: '🚌',
  plane: '✈️',
  bike: '🚲',
  parking: '🅿️',
  alert: '⚠️',
  medical: '🩺',
  phone: '📞',
  shield: '🛡️',
  map: '🗺️',
  utensils: '🍴',
  'shopping-bag': '🛍️',
  camera: '📷',
  image: '🖼️',
  info: 'ℹ️',
  book: '📘',
  link: '🔗',
  hero: '🖼️',
  text: '✍️',
  spacer: '↕️',
  palette: '🎨',
  globe: '🌍',
  mobile: '📱',
  rocket: '🚀',
  lock: '🔒',
}

export function mapAppIconToFa(icon: string) {
  return appIconFaMap[icon as AppIconName] ?? 'fa-circle'
}

export function mapAppIconToEmoji(icon: string) {
  return appIconEmojiMap[icon as AppIconName] ?? '•'
}
