'use client'

import type { LucideProps } from 'lucide-react'
import {
  AlertTriangle,
  Bike,
  Building2,
  Bus,
  CalendarCheck,
  Camera,
  CarFront,
  Coffee,
  CookingPot,
  Globe,
  House,
  ImageIcon,
  Info,
  KeyRound,
  Laptop,
  Leaf,
  Lock,
  MapPinned,
  Monitor,
  MoonStar,
  Palette,
  PenSquare,
  Phone,
  Plane,
  Rocket,
  Shield,
  Snowflake,
  Sparkles,
  SquareParking,
  Tv,
  Users,
  Utensils,
  WashingMachine,
  Wifi,
  Wind,
  Briefcase,
  Croissant,
  CreditCard,
  type LucideIcon,
} from 'lucide-react'

const iconMap: Record<string, LucideIcon> = {
  house: House,
  key: KeyRound,
  building: Building2,
  sparkles: Sparkles,
  users: Users,
  leaf: Leaf,
  wifi: Wifi,
  car: CarFront,
  coffee: Coffee,
  snow: Snowflake,
  flame: AlertTriangle,
  tv: Tv,
  kitchen: CookingPot,
  laptop: Laptop,
  washer: WashingMachine,
  wind: Wind,
  breakfast: Croissant,
  moon: MoonStar,
  luggage: Briefcase,
  cleaning: Sparkles,
  bus: Bus,
  plane: Plane,
  bike: Bike,
  parking: SquareParking,
  alert: AlertTriangle,
  medical: Shield,
  phone: Phone,
  shield: Shield,
  map: MapPinned,
  utensils: Utensils,
  camera: Camera,
  image: ImageIcon,
  info: Info,
  book: CalendarCheck,
  link: Sparkles,
  hero: ImageIcon,
  text: PenSquare,
  spacer: Monitor,
  palette: Palette,
  globe: Globe,
  mobile: Monitor,
  rocket: Rocket,
  lock: Lock,
  card: CreditCard,
}

export default function AppIcon({ name, ...props }: LucideProps & { name: string }) {
  const Icon = iconMap[name] ?? House
  return <Icon {...props} />
}
